### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by mauver** [ripio/rcn-token#16]
Hello, dev. 

I accidentally sent the my RCN tokens to contract address. 

I see the my token in your contract address, can i refund this? 

Please give me back tokens. 

I can't touch any other method about this problem, so I wrote on github, I am sorry.

Please check and refund, Thanks. 

This is my txid https://etherscan.io/tx/0xda740db578f92e860e938279821b66701b58b93ea11730744890bdf28e1a8b0c

**Comment by Agusx1211** [comment]
Hi Mauver,

There is no way to withdraw funds from the token contract; the token has no real owner, so no one (not even us) can make transfers from there.
